apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-project-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibtehal2122/final-project-app.git  # ğŸ‘ˆ Ù„ÙŠÙ†Ùƒ Ø§Ù„Ø±ÙŠØ¨Ùˆ Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©
    targetRevision: main
    path: helm  # ğŸ‘ˆ Ø§Ù„Ù…Ø³Ø§Ø± Ø§Ù„Ù„ÙŠ ÙÙŠÙ‡ Ø§Ù„Ù€ Chart.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: final-project # ğŸ‘ˆ Ø§Ù„Ù€ Namespace Ø§Ù„Ù„ÙŠ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ù‡ÙŠÙ†Ø²Ù„ ÙÙŠÙ‡
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ù‡ÙŠØ¹Ù…Ù„ Ø§Ù„Ù€ namespace Ù„Ùˆ Ù…Ø´ Ù…ÙˆØ¬ÙˆØ¯Ø©